
# ID: php
# Name: php
# URL: https://www.colourlovers.com/palette/101782/PHP
DAVE_COLOR_HOST_BG='16'
DAVE_COLOR_HOST_FG='255'
DAVE_COLOR_USER_BG='103'
DAVE_COLOR_USER_FG='255'
DAVE_COLOR_DIR_BG='104'
DAVE_COLOR_DIR_FG='000'
DAVE_COLOR_GIT_BG='189'
DAVE_COLOR_GIT_FG='000'
DAVE_COLOR_DATE_BG='188'
DAVE_COLOR_DATE_FG='000'
DAVE_COLOR_TIME_BG='16'
DAVE_COLOR_TIME_FG='255'
DAVE_COLOR_GIT_CLEAN='060'
DAVE_COLOR_GIT_DIRTY='000'
DAVE_SHOW_DATE='NO'
DAVE_SHOW_TIME='YES'
DAVE_NO_BLANK_LINE=''
DAVE_COLOR_END_BG='000'
